-- Setup Masters & Item Masters Schema Extension
CREATE TABLE IF NOT EXISTS item_masters (
    id VARCHAR(64) PRIMARY KEY,
    code VARCHAR(64) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(128),
    description TEXT,
    base_price NUMERIC(14, 2) DEFAULT 0.00,
    target_uom VARCHAR(32) DEFAULT 'KG',
    weight_kg NUMERIC(8, 3) DEFAULT 1.0,
    uom VARCHAR(32),
    coa_account_id VARCHAR(64),
    min_stock_threshold INTEGER DEFAULT 5,
    status VARCHAR(32) DEFAULT 'POSTED',
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE item_masters DISABLE ROW LEVEL SECURITY;

ALTER TABLE categories ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS quality_tier VARCHAR(32) DEFAULT 'CREAM';
ALTER TABLE categories ADD COLUMN IF NOT EXISTS sort_order INTEGER DEFAULT 1;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS status VARCHAR(32) DEFAULT 'POSTED';
ALTER TABLE categories ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;

ALTER TABLE sizes ADD COLUMN IF NOT EXISTS code VARCHAR(32);
ALTER TABLE sizes ADD COLUMN IF NOT EXISTS category VARCHAR(64) DEFAULT 'Tops / Universal';
ALTER TABLE sizes ADD COLUMN IF NOT EXISTS sort_order INTEGER DEFAULT 1;
ALTER TABLE sizes ADD COLUMN IF NOT EXISTS status VARCHAR(32) DEFAULT 'POSTED';
ALTER TABLE sizes ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;

ALTER TABLE label_grades ADD COLUMN IF NOT EXISTS code VARCHAR(32);
ALTER TABLE label_grades ADD COLUMN IF NOT EXISTS quality_tier VARCHAR(32) DEFAULT 'CREAM';
ALTER TABLE label_grades ADD COLUMN IF NOT EXISTS price_multiplier NUMERIC(8, 2) DEFAULT 1.0;
ALTER TABLE label_grades ADD COLUMN IF NOT EXISTS sort_order INTEGER DEFAULT 1;
ALTER TABLE label_grades ADD COLUMN IF NOT EXISTS status VARCHAR(32) DEFAULT 'POSTED';
ALTER TABLE label_grades ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;

ALTER TABLE brand_masters ADD COLUMN IF NOT EXISTS origin VARCHAR(64) DEFAULT 'USA';
ALTER TABLE brand_masters ADD COLUMN IF NOT EXISTS era VARCHAR(32) DEFAULT '90s';
ALTER TABLE brand_masters ADD COLUMN IF NOT EXISTS status VARCHAR(32) DEFAULT 'POSTED';
